timeout: no
interface_resolution: 1280x720

/Vale 0.1.0-alpha.0
    comment: Vale x64 for UEFI. Version 0.1.0-alpha.0. Copyright (c) 2026 Aerilyn Vale and contributers, GNU General Public License v3.0-or-later.
    protocol: limine
    path: boot():/boot/kernel.elf
    resolution: 1280x720
